# Site settings
title: Personal Blog
header-img: img/home-bg.jpg
email: slava.ustovytski@gmail.com
description: "Blog about technology, languages and open source projects"
baseurl: ""
url: "slavau.github.io"
twitter_username: SlavaUstovytski
github_username:  slavau

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
